lyceum/about/urls.py
from django.urls import path

import about.views as views


app_name = "about"

urlpatterns = [path("", views.description, name="description")]

lyceum/catalog/urls.py
__all__ = ["PositiveIntConverter"]

from converters.posint import PositiveIntConverter
from django.urls import path, re_path, register_converter

import catalog.views as views


app_name = "catalog"

register_converter(PositiveIntConverter, "posint")


urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("<int:item_id>/", views.item_detail, name="item_detail"),
    re_path(
        r"^re/(?P<re_item_id>[1-9]\d*)/$",
        views.re_item_detail,
        name="re_item_detail",
    ),
    path(
        "converter/<posint:conv_item_id>/",
        views.item_converter,
        name="item_converter",
    ),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views as views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="home"),
    path("coffee/", views.coffee, name="coffee"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path


urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

lyceum/templates/includes/footer.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <p class="col-md-4 mb-0 text-body-secondary"б id="yearify">&copy; {% now "Y" %} 000 "Дробь"</p>

  <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <img src="{%  static 'img/cat-in-tea.jpg' %}" width="240" alt="Картинка кота в чае">
  </a>

  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link px-2 text-body-secondary">{% trans "Главная" %}</a></li>
    <li class="nav-item"><a href="{% url 'catalog:item_list' %}" class="nav-link px-2 text-body-secondary">{% trans "Список товаров" %}</a></li>
    <li class="nav-item"><a href="{% url 'about:description' %}" class="nav-link px-2 text-body-secondary">{% trans "О проекте" %}</a></li>
  </ul>
</footer>

lyceum/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <img src="{%  static 'img/cat-boba-tea.jpg' %}" width="60" alt="Картинка кота, пьющего чай боба">
  </a>
  <div align="left">
    <button class="btn btn-secondary rounded-pill px-2" type="button" onclick="ToggleTheme()">Переключение темы</button>
    &nbsp
  </div>
  <script>
  function ToggleTheme() {
     var element = document.body;
     element.classList.toggle("dark-mode");
  }
  </script>
  {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link {% if view_name == 'homepage:home' %}active{% endif %}">{% trans "Главная" %}</a></li>
      <li class="nav-item"><a href="{% url 'catalog:item_list' %}" class="nav-link {% if view_name == 'catalog:item_list' %}active{% endif %}">{% trans "Список товаров" %}</a></li>
      <li class="nav-item"><a href="{% url 'about:description' %}" class="nav-link {% if view_name == 'about:description' %}active{% endif %}">{% trans "О проекте" %}</a></li>
    </ul>
  {% endwith %}
</header>

lyceum/templates/includes/item_card.html
<!DOCTYPE html>
<div>
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title" align="center">{{item.name}}</h5>
        <p class="card-text" align="center">{{item.category.name}}</p>
        <p class="card-text" align="center">{{item.tags.all | join:", "}}</p>
        <p class="card-text" align="center">{{ item.text|truncatewords_html:10|safe }}</p>
        <div align="center">
          <a href="{% url 'catalog:item_detail' item_id=item.id %}" class="btn btn-primary">Перейти к товару</a>
        </div>
      </div>
    </div>
  </div>
</div>