lyceum/about/urls.py
from django.urls import path

import about.views as views


app_name = "about"

urlpatterns = [path("", views.description, name="description")]

lyceum/catalog/urls.py
__all__ = ["PositiveIntConverter"]

from converters.posint import PositiveIntConverter
from django.urls import path, re_path, register_converter

import catalog.views as views


app_name = "catalog"

register_converter(PositiveIntConverter, "posint")


urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("<int:item_id>/", views.item_detail, name="item_detail"),
    re_path(
        r"^re/(?P<re_item_id>[1-9]\d*)/$",
        views.re_item_detail,
        name="re_item_detail",
    ),
    path(
        "converter/<posint:conv_item_id>/",
        views.item_converter,
        name="item_converter",
    ),
]

lyceum/feedback/urls.py
from django.urls import path

import feedback.views as views

app_name = "feedback"

urlpatterns = [path("", views.feedback, name="feedback")]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views as views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="home"),
    path("coffee/", views.coffee, name="coffee"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path


urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

lyceum/homepage/forms.py
__all__ = ["EchoForm"]

from django import forms


class EchoForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

lyceum/homepage/views.py
__all__ = ["home", "coffee"]

from django.http import Http404, HttpResponse
from django.shortcuts import render

from catalog.models import Item
from homepage.forms import EchoForm


def home(request):
    data = Item.objects.main_page()
    return render(request, "homepage/main.html", context={"items": data})


def coffee(request):
    return HttpResponse("Я чайник", status=418)


def echo(request):
    form = EchoForm(request.POST or None)
    return render(request, "homepage/echo.html", {"form": form})


def echo_submit(request):
    if request.method == "POST":
        return HttpResponse(request.POST["text"])
    raise Http404()

lyceum/templates/homepage/echo.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Echo {% endblock %}
{% block content %}
  <h1 align="center">Echo</h1>
  <div class="container">
    <form method="post" action="{% url 'homepage:echo_submit' %}">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
{% endblock %}

lyceum/templates/homepage/main.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block title %} Главная {% endblock %}
{% block content %}
{% load static %}
  <h1 align="center">Главная страница сайта</h1>
  <div align="center">
    <h3>Занимаемся продажей пищевых и бытовых товаров с 2023, подробнее со списком вы можете в каталоге.</h3>
  </div>
  <br>
  <div class="row  row-cols-1 row-cols-md-2 row-cols-lg-4 row-cols-xl-6 g-4">
    {% for item in items %}
      {% include "includes/item_card.html" %}
    {% empty %}
      <h2>Товаров нет, но вы держитесь</h2>
    {% endfor %}
  </div>
  <br>
  <div align="center">
    <div>
      <a href="{% url 'catalog:item_list' %}">
        <button class="btn btn-lg btn-info rounded-pill px-3" type="button">ТЫК (Каталог)</button>
      </a>
    </div>
    <br>
    <div>
      <a href="{% url 'feedback:feedback' %}">
        <button class="btn btn-lg btn-info rounded-pill px-3" type="button">Напишите о том, какие мы крутые</button>
      </a>
    </div>
  </div>
{% endblock %}